import { Utility } from '../types';

export const UTILITIES: Utility[] = [
    {
        id: 'image-to-pdf',
        title: 'Image to PDF',
        description: 'Convert images to PDF documents',
        icon: '📄',
        screen: 'ImageToPdf',
        gradient: ['#6366F1', '#8B5CF6'],
    },
    {
        id: 'qr-generator',
        title: 'QR Generator',
        description: 'Create QR codes instantly',
        icon: '🔲',
        screen: 'QRGenerator',
        gradient: ['#EC4899', '#F472B6'],
    },
    {
        id: 'qr-scanner',
        title: 'QR Scanner',
        description: 'Scan and decode QR codes',
        icon: '📷',
        screen: 'QRScanner',
        gradient: ['#10B981', '#34D399'],
    },
    {
        id: 'unit-converter',
        title: 'Unit Converter',
        description: 'Convert units easily',
        icon: '🔄',
        screen: 'UnitConverter',
        gradient: ['#F59E0B', '#FBBF24'],
    },
    {
        id: 'currency-converter',
        title: 'Currency Converter',
        description: 'Real-time currency rates',
        icon: '💱',
        screen: 'CurrencyConverter',
        gradient: ['#3B82F6', '#60A5FA'],
    },
    {
        id: 'text-tools',
        title: 'Text Tools',
        description: 'Word counter & formatters',
        icon: '✏️',
        screen: 'TextTools',
        gradient: ['#8B5CF6', '#A78BFA'],
    },
    {
        id: 'image-compressor',
        title: 'Image Compressor',
        description: 'Reduce image file sizes',
        icon: '🗜️',
        screen: 'ImageCompressor',
        gradient: ['#EF4444', '#F87171'],
    },
    {
        id: 'color-picker',
        title: 'Color Picker',
        description: 'Extract colors from images',
        icon: '🎨',
        screen: 'ColorPicker',
        gradient: ['#14B8A6', '#2DD4BF'],
    },
    {
        id: 'password-generator',
        title: 'Password Generator',
        description: 'Generate secure passwords',
        icon: '🔐',
        screen: 'PasswordGenerator',
        gradient: ['#059669', '#10B981'],
    },
    {
        id: 'calculator',
        title: 'Calculator',
        description: 'Basic math calculations',
        icon: '🧮',
        screen: 'Calculator',
        gradient: ['#7C3AED', '#8B5CF6'],
    },
];
