import { Utility } from '../types';

export const UTILITIES: Utility[] = [
    {
        id: 'image-to-pdf',
        title: 'Image to PDF',
        description: 'Convert images to PDF documents',
        icon: '📄',
        screen: 'ImageToPdf',
        gradient: ['#6366F1', '#8B5CF6'],
    },
    {
        id: 'qr-scanner',
        title: 'QR Scanner',
        description: 'Scan and decode QR codes',
        icon: '📷',
        screen: 'QRScanner',
        gradient: ['#10B981', '#34D399'],
    },
    {
        id: 'qr-generator',
        title: 'QR Generator',
        description: 'Create QR codes instantly',
        icon: '🔲',
        screen: 'QRGenerator',
        gradient: ['#EC4899', '#F472B6'],
    },
    {
        id: 'expense-tracker',
        title: 'Expense Tracker',
        description: 'Log daily spending on device',
        icon: '💸',
        screen: 'ExpenseTracker',
        gradient: ['#F43F5E', '#FB7185'],
    },
    {
        id: 'percentage-calculator',
        title: 'Percentage Calculator',
        description: '% of a number, increase & decrease',
        icon: '➗',
        screen: 'PercentageCalculator',
        gradient: ['#8B5CF6', '#A78BFA'],
    },
    {
        id: 'currency-converter',
        title: 'Currency Converter',
        description: 'Latest currency rates',
        icon: '💱',
        screen: 'CurrencyConverter',
        gradient: ['#3B82F6', '#60A5FA'],
    },
    {
        id: 'unit-converter',
        title: 'Unit Converter',
        description: 'Convert units easily',
        icon: '🔄',
        screen: 'UnitConverter',
        gradient: ['#F59E0B', '#FBBF24'],
    },
    {
        id: 'gst-calculator',
        title: 'GST / Tax Calculator',
        description: 'Add or extract sales tax',
        icon: '🧾',
        screen: 'GstCalculator',
        gradient: ['#BE185D', '#F472B6'],
    },
    {
        id: 'loan-calculator',
        title: 'Loan / EMI Calculator',
        description: 'Monthly EMI & total interest',
        icon: '🏦',
        screen: 'LoanCalculator',
        gradient: ['#4338CA', '#6366F1'],
    },
    {
        id: 'salary-calculator',
        title: 'Salary Calculator',
        description: 'Hourly, daily, monthly & yearly',
        icon: '💼',
        screen: 'SalaryCalculator',
        gradient: ['#1D4ED8', '#60A5FA'],
    },
    {
        id: 'fuel-calculator',
        title: 'Fuel Calculator',
        description: 'Trip cost & km per liter',
        icon: '⛽',
        screen: 'FuelCalculator',
        gradient: ['#EA580C', '#FB923C'],
    },
    {
        id: 'savings-calculator',
        title: 'Savings Calculator',
        description: 'Compound interest & future value',
        icon: '📈',
        screen: 'SavingsCalculator',
        gradient: ['#059669', '#34D399'],
    },
    {
        id: 'discount-calculator',
        title: 'Discount Calculator',
        description: 'Sale price, tax & savings',
        icon: '🏷️',
        screen: 'DiscountCalculator',
        gradient: ['#DB2777', '#F472B6'],
    },
    {
        id: 'bmi-calculator',
        title: 'BMI Calculator',
        description: 'Check your body mass index',
        icon: '⚖️',
        screen: 'BmiCalculator',
        gradient: ['#06B6D4', '#22D3EE'],
    },
    {
        id: 'calorie-calculator',
        title: 'Calorie Calculator',
        description: 'BMR, maintain, lose or gain',
        icon: '🔥',
        screen: 'CalorieCalculator',
        gradient: ['#DC2626', '#FB7185'],
    },
    {
        id: 'image-compressor',
        title: 'Image Compressor',
        description: 'Reduce image file sizes',
        icon: '🗜️',
        screen: 'ImageCompressor',
        gradient: ['#EF4444', '#F87171'],
    },
    {
        id: 'password-generator',
        title: 'Password Generator',
        description: 'Generate secure passwords',
        icon: '🔐',
        screen: 'PasswordGenerator',
        gradient: ['#059669', '#10B981'],
    },
    {
        id: 'notes',
        title: 'Notes',
        description: 'Quick notes saved on device',
        icon: '📝',
        screen: 'Notes',
        gradient: ['#F97316', '#FB923C'],
    },
    {
        id: 'checklist',
        title: 'Checklist',
        description: 'To-dos saved on this device',
        icon: '✅',
        screen: 'Checklist',
        gradient: ['#16A34A', '#4ADE80'],
    },
    {
        id: 'world-clock',
        title: 'World Clock',
        description: 'Time in cities worldwide',
        icon: '🌍',
        screen: 'WorldClock',
        gradient: ['#0EA5E9', '#38BDF8'],
    },
    {
        id: 'area-calculator',
        title: 'Area Calculator',
        description: 'Rooms, land & marla',
        icon: '📐',
        screen: 'AreaCalculator',
        gradient: ['#0D9488', '#2DD4BF'],
    },
    {
        id: 'tip-calculator',
        title: 'Tip Calculator',
        description: 'Split bills & tip amounts',
        icon: '💵',
        screen: 'TipCalculator',
        gradient: ['#22C55E', '#4ADE80'],
    },
    {
        id: 'age-calculator',
        title: 'Age Calculator',
        description: 'Find exact age from DOB',
        icon: '🎂',
        screen: 'AgeCalculator',
        gradient: ['#D946EF', '#E879F9'],
    },
    {
        id: 'date-calculator',
        title: 'Date Calculator',
        description: 'Days between dates & date math',
        icon: '📅',
        screen: 'DateCalculator',
        gradient: ['#14B8A6', '#5EEAD4'],
    },
    {
        id: 'countdown',
        title: 'Countdown',
        description: 'Days left until an event',
        icon: '⏳',
        screen: 'Countdown',
        gradient: ['#7C3AED', '#C084FC'],
    },
    {
        id: 'calculator',
        title: 'Calculator',
        description: 'Basic math calculations',
        icon: '🧮',
        screen: 'Calculator',
        gradient: ['#7C3AED', '#8B5CF6'],
    },
    {
        id: 'stopwatch',
        title: 'Stopwatch & Timer',
        description: 'Track time with laps',
        icon: '⏱️',
        screen: 'Stopwatch',
        gradient: ['#0284C7', '#38BDF8'],
    },
];
